---
title: "CodeBook"
author: "dustinmw"
date: "4/16/2020"
output: html_document
---



#Key Identification
  
  "subject" - The ID of the test subject
  "activity" - The type of activity performed when the corresponding measurements were taken


#Measurements Collected
  
  "TimeBodyAccelerometer-mean()-X"
  "TimeBodyAccelerometer-mean()-Y"
  "TimeBodyAccelerometer-mean()-Z"
  "TimeBodyAccelerometer-std()-X"
  "TimeBodyAccelerometer-std()-Y"
  "TimeBodyAccelerometer-std()-Z"
  "TimeGravityAccelerometer-mean()-X"
  "TimeGravityAccelerometer-mean()-Y"
  "TimeGravityAccelerometer-mean()-Z"
  "TimeGravityAccelerometer-std()-X"
  "TimeGravityAccelerometer-std()-Y"
  "TimeGravityAccelerometer-std()-Z"
  "TimeBodyAccelerometerJerk-mean()-X"
  "TimeBodyAccelerometerJerk-mean()-Y"
  "TimeBodyAccelerometerJerk-mean()-Z"
  "TimeBodyAccelerometerJerk-std()-X"
  "TimeBodyAccelerometerJerk-std()-Y"
  "TimeBodyAccelerometerJerk-std()-Z"
  "TimeBodyGyroscope-mean()-X"
  "TimeBodyGyroscope-mean()-Y"
  "TimeBodyGyroscope-mean()-Z"
  "TimeBodyGyroscope-std()-X"
  "TimeBodyGyroscope-std()-Y"
  "TimeBodyGyroscope-std()-Z"
  "TimeBodyGyroscopeJerk-mean()-X"
  "TimeBodyGyroscopeJerk-mean()-Y"
  "TimeBodyGyroscopeJerk-mean()-Z"
  "TimeBodyGyroscopeJerk-std()-X"
  "TimeBodyGyroscopeJerk-std()-Y"
  "TimeBodyGyroscopeJerk-std()-Z"
  "TimeBodyAccelerometerMagnitude-mean()"
  "TimeBodyAccelerometerMagnitude-std()"
  "TimeGravityAccelerometerMagnitude-mean()"
  "TimeGravityAccelerometerMagnitude-std()"
  "TimeBodyAccelerometerJerkMagnitude-mean()"
  "TimeBodyAccelerometerJerkMagnitude-std()"
  "TimeBodyGyroscopeMagnitude-mean()"
  "TimeBodyGyroscopeMagnitude-std()"
  "TimeBodyGyroscopeJerkMagnitude-mean()"
  "TimeBodyGyroscopeJerkMagnitude-std()"
  "FrequencyBodyAccelerometer-mean()-X"
  "FrequencyBodyAccelerometer-mean()-Y"
  "FrequencyBodyAccelerometer-mean()-Z"
  "FrequencyBodyAccelerometer-std()-X"
  "FrequencyBodyAccelerometer-std()-Y"
  "FrequencyBodyAccelerometer-std()-Z"
  "FrequencyBodyAccelerometerJerk-mean()-X"
  "FrequencyBodyAccelerometerJerk-mean()-Y"
  "FrequencyBodyAccelerometerJerk-mean()-Z"
  "FrequencyBodyAccelerometerJerk-std()-X"
  "FrequencyBodyAccelerometerJerk-std()-Y"
  "FrequencyBodyAccelerometerJerk-std()-Z"
  "FrequencyBodyGyroscope-mean()-X"
  "FrequencyBodyGyroscope-mean()-Y"
  "FrequencyBodyGyroscope-mean()-Z"
  "FrequencyBodyGyroscope-std()-X"
  "FrequencyBodyGyroscope-std()-Y"
  "FrequencyBodyGyroscope-std()-Z"
  "FrequencyBodyAccelerometerMagnitude-mean()"
  "FrequencyBodyAccelerometerMagnitude-std()"
  "FrequencyBodyAccelerometerJerkMagnitude-mean()"
  "FrequencyBodyAccelerometerJerkMagnitude-std()"
  "FrequencyBodyGyroscopeMagnitude-mean()"
  "FrequencyBodyGyroscopeMagnitude-std()"
  "FrequencyBodyGyroscopeJerkMagnitude-mean()"
  "FrequencyBodyGyroscopeJerkMagnitude-std()"



#Activity Labels


  WALKING (value 1): subject was walking during the test
  WALKING_UPSTAIRS (value 2): subject was walking up a staircase during the test
  WALKING_DOWNSTAIRS (value 3): subject was walking down a staircase during the test
  SITTING (value 4): subject was sitting during the test
  STANDING (value 5): subject was standing during the test
  LAYING (value 6): subject was laying down during the 
